import Nav from "../navbar/Nav"
import { Link } from "react-router-dom"
import { useEffect } from "react"
import banner from './assets/terms.webp'

const TermsConditions = () => {

  useEffect(() => {
    window.scrollTo(0, 0)
  }, [])


  return (
    <>
      <div className="h-[380px] md:h-[480px] w-full bg-cover bg-center bg-no-repeat flex items-center justify-center"
        style={{ backgroundImage: `url(${banner})` }}>
        <div className="bg-black/20 w-full pt-[96px] absolute top-0">
          <Nav />
        </div>
        <p className="text-white text-[clamp(30px,3.2vw,55px)] font-semibold">Terms and Conditions</p>
      </div>
      <div className="w-full">
        <div className="w-full max-w-[1280px] p-4 py-20 mx-auto">
          <h2 className="text-blue-500 font-semibold mb-1 mt-8 text-lg">AGREEMENT</h2>
            <p className="leading-7">The terms and conditions set forth on the Front Page and below (the “Service Terms”); together will govern Customer’s use of the services identified on the attached Front Page.</p>

            <h2 className="text-blue-500 font-semibold mb-1 mt-8 text-lg">NET AGREEMENT</h2>
            <p className="leading-7">THIS AGREEMENT IS NON-CANCELABLE FOR THE ENTIRE AGREEMENT TERM. YOU AGREE THAT YOU ARE UNCONDITIONALLY OBLIGATED TO PAY ALL AMOUNTS DUE UNDER THIS AGREEMENT FOR THE ENTIRE TERM. YOU AGREE THIS AGREEMENT MY BE CHANGED BASED ON YOUR BUSINESS NEEDS VERBALLY AND/OR AGREED THROUGH EMAIL.  YOU AGREE THESE CHANGES ARE BOUND BY SAID AGREEMENT BASED ON THE CHANGES MADE ON YOUR INVOICES EITHER BY QUANITY OR PRICE OR BOTH WITHOUT REQUIRING A WRITTEN CHANGE IN AGREEMENT, YOU AGREE TO PAY ALL INVOICES INCLUDING CHANGES THEREIN AND BY PAYING INVOICES ARE BOUND BY SUCH CHANGES.  YOU ARE NOT ENTITLED TO REDUCE OR SET-OFF AGAINST AMOUNTS DUE UNDER THIS AGREEMENT FOR ANY REASON. THIS AGREEMENT MAY INCREASE OR DECREASE WITHOUT REQUIRING AN UPDATE, CUSTOMER IS UNCONDITIONALLY RESPONSIBLE FOR THE INCREASE IN MONTHLY COST.</p>

            <h2 className="text-blue-500 font-semibold mb-1 mt-8 text-lg">TARIFFS/SERVICE GUIDE</h2>
            <p className="leading-7">If Customer is purchasing any Services that are regulated by the FCC or any state regulatory body (“Regulated Services”) then Customer’s use of such Regulated Services is subject to the regulations of the FCC and the regulatory body of the state in which the Customer location receiving these Regulated Services is located (which regulations are subject to change), as well as the rates, terms, and conditions contained in tariffs on the file with state and federal regulatory authorities.</p>

            <h2 className="text-blue-500 font-semibold mb-1 mt-8 text-lg">PBX USAGE AND E911 SERVICES</h2>
            <p className="leading-7">PBX will not have battery backup. Customer is responsible for battery backup for all equipment. In the event of a power outage, customer’s telephone services using <strong>FD360</strong>’s PBX will only continue to operate if there is a battery backup in place for a period determined by the battery backup, this assumes no interruption in internet services provided by others. The duration of service during a power outage using any other equipment will depend on customer’s battery backup choice. If the PBX that supplies your telephone service is disconnected or removed and/or the battery is not charged or is damaged, service, including access to 911 or E911 will not be available. <strong>FD360</strong> shall not be responsible or liable for any failure to receive service or for the failure of any 911 or E911 call if customer removes or disconnects the PBX, Battery backup or if customer fails to charge the battery for said devices at any time during the term of this agreement or thereafter while <strong>FD360</strong> is providing services. <strong>FD360</strong> uses your telephone service address to identify your location for E911 service. Please notify <strong>FD360</strong> if you would like to move or relocate your telephone service. It can take up to 72 hours for your new address to be updated.</p>

            <h2 className="text-blue-500 font-semibold mb-1 mt-8 text-lg">E911 DISCLAIMER</h2>
            <p className="leading-7">You may not be able to reach the correct emergency services location if your move your phone to a location different from the physical address you initially registered. This address unless otherwise noted is shown on the front of this agreement. It is important that you register accurate physical location information every time you move the Equipment associated with your Hosted PBX service. If you move your Equipment to another location without notifying us, when you dial 911 you may not be able to reach the correct emergency services location or any emergency personnel at all. Even if you do reach emergency personnel, if you have not provided accurate physical location information you will not be calling the emergency personnel near your actual current location and this emergency personnel may not be able to transfer your call or respond to your emergency. It is important that you register an accurate physical location when you initiate your service and every time you move the Equipment associated with services provided by us. When you change your location, it may take up to 72 hours for your location to change to be reflected in our records. During that time, you may not be able to reach the correct emergency services center or any emergency service provider by dialing 911.</p>

            <h2 className="text-blue-500 font-semibold mb-1 mt-8 text-lg">SERVICE START DATE AND TERM</h2>
            <p className="leading-7">This Agreement shall be effective upon execution by the parties. The “Initial Term” shall begin upon installation of Service and shall continue for the applicable Term commitment set forth on the Front Page; provided that if Customer delays installation or is not ready to receive Service on the agreed-upon installation date, <strong>FD360</strong> may begin billing for Services on the date of Service would have been installed. <strong>FD360</strong> shall use reasonable efforts to make the Services available by the requested service date. <strong>FD360</strong> shall not be liable for damages resulting from delays in meeting service dates due to construction delays or reasons beyond its control. If Customer delays installation for a period of three (3) months or longer after the parties’ execution of this Agreement, <strong>FD360</strong> reserves the right to terminate this Agreement immediately at any time thereafter and Customer shall be responsible for the full amount of construction costs and any other related costs incurred by <strong>FD360</strong> as of the date of termination. After the initial term, this agreement shall automatically renew for one (1) year terms (each an “extended term”) unless a party gives the other party written termination notice at least thirty (30) days prior to the expiration of the initial term or then current extended term. “Term” shall mean the Initial Term and Extended Term (s), if any. <strong>FD360</strong> reserves the right to increase rates for all Services by no more than ten percent (10%) during any Extended Term by providing Customer with at least sixty (60) days written notice of such rate increase. This limitation on rate increases shall not apply to FCC and tax related charges and fees.</p>

            <h2 className="text-blue-500 font-semibold mb-1 mt-8 text-lg">SOFTWARES AND USES</h2>
            <p className="leading-7">This Agreement may include “software’s for customer use” such as but not limited to Microsoft Office 365, Google Workspace, SEO applications and others, hereafter “software’s” These software’s are provided by <strong>FD360</strong> for your use respectively. <strong>FD360</strong> will be responsible for the security and safeguarding these software’s. <strong>FD360</strong> in some cases with software’s will serve as a tenant and provide billing services. Customer is responsible for all billing, billing is passed on to customer from <strong>FD360</strong> and <strong>FD360</strong> will keep any third-party billing current to prevent any billing issues to client’s software’s. Customer is bound by third party agreements including respective terms if imposed. Customer will keep <strong>FD360</strong> current on all software’s at all times. Customer understands if billing is behind it could cause a suspension in software’s product. <strong>FD360</strong> will not offboard any software’s if payment is past due, once current <strong>FD360</strong> shall be required to offboard when requested all software’s.</p>

            <h2 className="text-blue-500 font-semibold mb-1 mt-8 text-lg">END OF TERM</h2>
            <p className="leading-7">At the end of the term of this Agreement (or any renewal term) (the “End Date”), this Agreement will renew for an additional one-year period under the same terms unless a) you provide us written notice, at least 60 days prior to the End Date, of your intent to terminate services and return any Equipment. and b) you timely return the Equipment to the location designated by us, at your expense. If the returned Equipment is not immediately available for use by another without need of repair, you will reimburse us for all repair costs. You cannot pay off this Agreement or return the Equipment prior to the End Date without our consent. If we consent, we may charge you, in addition to other amounts owed, an early termination fee equal to 5% of the price of the services and equipment herein. Customer understands in order to end the contract account balance must be current and paid in full. Customer agrees to the remaining payments through the end of term date. Payment is determined by the last 90-day average billing.</p>

            <p className="leading-7">Unless otherwise expressly stated in this Agreement, you will be obligated to pay a termination fee equal to the nonrecurring charges (if unpaid) and 100% of the monthly recurring charges for the terminated Service(s) multiplied by the number of full months remaining in the Term. This provision survives termination of the Agreement.</p>

            <h2 className="text-blue-500 font-semibold mb-1 mt-8 text-lg">PAYMENT</h2>
            <p className="leading-7">Customer shall pay for all monthly Service charges, plus one-time set-up, installation and/or construction charges. Unless stated otherwise herein, monthly charges for Services shall begin upon installation of Service, and installation charges, if any, shall be due upon completion of installation. Any amount not received by the due date shown on the applicable invoice will be subject to interest and a late charge no greater than the maximum rate allowed by law. Customer acknowledges and agrees that if Customer fails to pay any amounts when due and fails to cure such non-payment upon receipt of written notice of non-payment from <strong>FD360</strong>, Customer will be deemed to have terminated this Agreement and will be obligated to pay their termination fees described herein above. If applicable to the Service, Customer shall pay sales, use, gross receipts and excise taxes, access fees and all other fees, universal service fund assessments, 911 fees, franchise fees bypass and other local, state and Federal taxes or charges and deposits, imposed on the use of the Services. Taxes will be separately stated on the Customer’s invoice. No interest will be paid on deposits unless required by law.</p>

            <h2 className="text-blue-500 font-semibold mb-1 mt-8 text-lg">SERVICE AND INSTALLATION</h2>
            <p className="leading-7"><strong>FD360</strong> shall provide Customer with the Services identified on the Front Page and may provide related facilities and equipment, the ownership of which shall be retained by <strong>FD360</strong> (the “<strong>FD360</strong> Equipment”), or for certain Services, Customer may purchase equipment from <strong>FD360</strong> (“Customer Purchased Equipment”). Customer may use the Services for any lawful purpose, provided that such purpose (a) does not interfere or impair the <strong>FD360</strong> network or <strong>FD360</strong> Equipment and (b) complies with state and Federal law. Customer shall use the <strong>FD360</strong> Equipment only for the purpose of receiving the Services. Customer shall use Customer Purchased Equipment in accordance with the terms of the related equipment purchase agreement. Unless provided otherwise herein, <strong>FD360</strong> shall use commercially reasonable efforts to maintain the Services in accordance with applicable performance standards.</p>

            <h2 className="text-blue-500 font-semibold mb-1 mt-8 text-lg">E-RATE CUSTOMERS</h2>
            <p className="leading-7">If Customer is an educational institution, library or other entity that qualifies as an applicant seeking reimbursement under the Federal Universal Services Fund Schools and Libraries Program (collectively, “E-Rate Customers”) additional terms may apply.</p>

            <h2 className="text-blue-500 font-semibold mb-1 mt-8 text-lg">LIMITATION OF LIABILITY</h2>
            <p className="leading-7"><strong>FD360</strong> and/or its agents shall not be liable for damages for failure to furnish or interruption of any services nor shall <strong>FD360</strong> or its agents be responsible for failure or errors in signal transmissions, loss of data, files or software damage regardless of the cause. <strong>FD360</strong> shall not be liable for damage to property or for injury to any person arising from the installation or removal of the equipment unless caused by negligence of <strong>FD360</strong>. Under no circumstances will <strong>FD360</strong> be liable for any indirect, incidental, special or consequential damages, including lost profits, arising from this agreement or its provisions of the services.</p>

            <h2 className="text-blue-500 font-semibold mb-1 mt-8 text-lg">EQUIPMENT USE</h2>
            <p className="leading-7">You will keep the Equipment in good working order, use it for business purposes only and not modify or move it from its initial location without our consent. If we have entered into a separate arrangement with you for maintenance with respect to the Equipment, payments under this Agreement may include amounts owed under that arrangement, which amounts may be invoiced as one payment for your convenience. These amounts may include a fee for the remote monitoring of certain telecommunication systems, servers, printers, and/or multi-functional devices included as a part of the Equipment under this Agreement (each a “Device”) at a charge of $4.00 per month per Device. Unless otherwise noted herein, all equipment will remain the property of <strong>FD360</strong> and shall be returned at customer expense upon termination of this Agreement.</p>

            <h2 className="text-blue-500 font-semibold mb-1 mt-8 text-lg">WARRANTIES</h2>
            <p className="leading-7">Except as provided herein, there are no other agreements, warranties or representations, express or implied, either in fact or by operation of law, statutory or otherwise, including warranties of merchantability and fitness for a particular purpose, relating to the services. Services provided are a best-efforts service and <strong>FD360</strong> does not warrant that the services, equipment or software shall be error-free or without interruption. Internet speeds will vary. <strong>FD360</strong> makes no warranty as to transmission or upstream or downstream speeds of the network. Notwithstanding anything to the contrary, this agreement may be signed in connection with a finance agreement; if so, the finance agreement's specific terms take priority over this agreement.</p>

    
        </div>
      </div>
    </>
  )
}

export default TermsConditions